#?? ???? ???? username, password ?? ???? root ??? ?? git ignore?? ?? ???.
spring:
  datasource:
    driver-class-name: 'org.mariadb.jdbc.Driver'
    url: 'jdbc:mariadb://localhost:3306/jm_universe'
    username: 'root'
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MariaDBDialect'
        show_sql: true
        format_sql: true
        use_sql_comments: true